"""Common case-management public API."""

from .repository import (
    ArchivedCaseReadOnlyError,
    CaseAlreadyExistsError,
    CaseError,
    CaseNotFoundError,
    InvalidCaseError,
)
from .partition_store import (
    attach_partition_report,
    load_latest_partition_manifest,
    save_partition_run,
)
from .sightings import (
    clear_sightings,
    delete_sighting,
    get_cgi_group,
    list_cgi_groups,
    list_sightings,
    save_cgi_group,
    replace_simple_sightings,
    save_sighting,
)
from .service import (
    archive_case,
    case_health,
    case_directory,
    case_evidence_dir,
    case_report_dir,
    create_case,
    ensure_case_writable,
    generate_case_id,
    get_case_overview,
    list_case_reports,
    list_cases,
    log_case_event,
    open_case,
    reopen_case,
    register_analysis_run,
    register_evidence,
    register_report,
    register_target,
    verify_case_audit,
)

__all__ = [
    "CaseError",
    "ArchivedCaseReadOnlyError",
    "CaseNotFoundError",
    "CaseAlreadyExistsError",
    "InvalidCaseError",
    "create_case",
    "ensure_case_writable",
    "generate_case_id",
    "get_case_overview",
    "open_case",
    "list_cases",
    "archive_case",
    "reopen_case",
    "case_health",
    "verify_case_audit",
    "case_directory",
    "case_evidence_dir",
    "case_report_dir",
    "register_target",
    "register_evidence",
    "register_report",
    "register_analysis_run",
    "list_case_reports",
    "log_case_event",
    "save_cgi_group",
    "list_cgi_groups",
    "get_cgi_group",
    "save_sighting",
    "replace_simple_sightings",
    "clear_sightings",
    "list_sightings",
    "delete_sighting",
    "save_partition_run",
    "attach_partition_report",
    "load_latest_partition_manifest",
]
